name: Security laravel

on:
  push:
    branches:
      - master

jobs:
  security_tests:
    name: Security Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0.2'  

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"
        mv composer.phar /usr/local/bin/composer

    - name: Install dependencies
      run: composer install

    - name: Run Laravel Dusk tests
      run: php artisan dusk

    - name: Run PHPStan for static analysis
      run: vendor/bin/phpstan analyse
